# Site settings
name: campaul [dot] net
title: Software Engineer @ Yelp. I Build Things.
email: cpaul37@gmail.com
description:
baseurl:
url: http://campaul.github.io

# Build settings
markdown: redcarpet
permalinks: pretty

# Octopress settings
permalink: /blog/:year/:month/:day/:title/
twitter_user: cpaul37
github_user: campaul
